services:
  postgres:
    image: postgres:18
    # container_name: postgres_pa26
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:8
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

  node:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - ${NODE_PORT}:3000
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
